import { Product } from '@/types';

export const categories = [
  {
    id: 'kitchen',
    name: 'Kitchen Appliances',
    nameFa: 'لوازم آشپزخانه',
    subcategories: ['Refrigerators', 'Microwave Ovens', 'Dishwashers', 'Cooktops']
  },
  {
    id: 'cooling',
    name: 'Cooling & Air Treatment',
    nameFa: 'سرمایش و تهویه',
    subcategories: ['Air Conditioners', 'Air Coolers', 'Air Purifiers', 'Fans']
  },
  {
    id: 'washing',
    name: 'Washing & Cleaning',
    nameFa: 'شستشو و نظافت',
    subcategories: ['Washing Machines', 'Dryers', 'Vacuum Cleaners']
  },
  {
    id: 'personal-care',
    name: 'Personal Care',
    nameFa: 'مراقبت شخصی',
    subcategories: ['Hair Dryers', 'Trimmers', 'Electric Shavers']
  }
];

export const enhancedProducts: Product[] = [
  {
    id: 'p1',
    sku: 'SAM-RF-600',
    name: 'یخچال فرانسوی سامسونگ',
    nameEn: 'Samsung French Door Refrigerator',
    slug: 'samsung-french-door-refrigerator',
    description: 'یخچال فرانسوی پریمیوم با ظرفیت 600 لیتر، فناوری Twin Cooling Plus، دیسپنسر آب و یخ، و کمپرسور اینورتر دیجیتال برای بهره‌وری انرژی.',
    descriptionEn: 'Premium French door refrigerator with 600L capacity, featuring Twin Cooling Plus technology, ice & water dispenser, and digital inverter compressor for energy efficiency.',
    shortDescription: 'یخچال 600 لیتری با Twin Cooling Plus',
    shortDescriptionEn: '600L French Door Refrigerator with Twin Cooling Plus',
    brand: 'Samsung',
    category: 'لوازم آشپزخانه',
    categoryEn: 'Kitchen Appliances',
    subCategory: 'یخچال',
    subCategoryEn: 'Refrigerators',
    price: 89999000,
    discountPrice: 74999000,
    discountPercent: 17,
    stock: 12,
    images: ['/placeholder.svg', '/placeholder.svg', '/placeholder.svg'],
    mainImage: '/placeholder.svg',
    features: {
      'ظرفیت': '600 لیتر',
      'رتبه انرژی': 'A++',
      'فناوری': 'Twin Cooling Plus',
      'کمپرسور': 'اینورتر دیجیتال',
      'گارانتی': '2 سال'
    },
    featuresEn: {
      'Capacity': '600L',
      'Energy Rating': 'A++',
      'Technology': 'Twin Cooling Plus',
      'Compressor': 'Digital Inverter',
      'Warranty': '2 Years'
    },
    colors: ['Silver', 'Black', 'White'],
    rating: 4.7,
    reviewCount: 234,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    sku: 'LG-WM-8KG',
    name: 'ماشین لباسشویی ال جی',
    nameEn: 'LG Front Load Washing Machine',
    slug: 'lg-front-load-washing-machine',
    description: 'ماشین لباسشویی پیشرفته 8 کیلوگرمی با فناوری AI DD، شستشوی بخار، و TurboWash برای شستشوی سریع‌تر. رتبه انرژی A+++.',
    descriptionEn: 'Advanced 8kg front load washing machine with AI DD technology, Steam wash, and TurboWash for faster cleaning. Energy efficient A+++ rating.',
    shortDescription: 'ماشین لباسشویی 8 کیلو با AI DD',
    shortDescriptionEn: '8kg Front Load with AI DD Technology',
    brand: 'LG',
    category: 'شستشو و نظافت',
    categoryEn: 'Washing & Cleaning',
    subCategory: 'ماشین لباسشویی',
    subCategoryEn: 'Washing Machines',
    price: 54999000,
    discountPrice: 46999000,
    discountPercent: 15,
    stock: 8,
    images: ['/placeholder.svg', '/placeholder.svg'],
    mainImage: '/placeholder.svg',
    features: {
      'ظرفیت': '8 کیلوگرم',
      'رتبه انرژی': 'A+++',
      'فناوری': 'AI DD',
      'سرعت چرخش': '1400 دور',
      'گارانتی': '2 سال + 10 سال موتور'
    },
    featuresEn: {
      'Capacity': '8 kg',
      'Energy Rating': 'A+++',
      'Technology': 'AI DD',
      'Spin Speed': '1400 RPM',
      'Warranty': '2 Years + 10 Years Motor'
    },
    colors: ['White', 'Silver'],
    rating: 4.6,
    reviewCount: 189,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    sku: 'DAIKIN-AC-1.5T',
    name: 'کولر گازی دایکین 1.5 تن',
    nameEn: 'Daikin 1.5 Ton Split AC',
    slug: 'daikin-split-ac-1-5-ton',
    description: 'کولر گازی اسپلیت اینورتر با کندانسور مسی، فیلتر PM 2.5، و فناوری چشم هوشمند. رتبه انرژی 5 ستاره با کویل 100% مسی.',
    descriptionEn: 'Inverter split AC with copper condenser, PM 2.5 filter, and intelligent eye technology. Energy efficient 5-star rated with 100% copper coil.',
    shortDescription: 'کولر 1.5 تن اینورتر با فیلتر PM 2.5',
    shortDescriptionEn: '1.5 Ton Inverter AC with PM 2.5 Filter',
    brand: 'Daikin',
    category: 'سرمایش و تهویه',
    categoryEn: 'Cooling & Air Treatment',
    subCategory: 'کولر گازی',
    subCategoryEn: 'Air Conditioners',
    price: 42999000,
    discountPrice: 38999000,
    discountPercent: 9,
    stock: 15,
    images: ['/placeholder.svg'],
    mainImage: '/placeholder.svg',
    features: {
      'ظرفیت': '1.5 تن',
      'رتبه انرژی': '5 ستاره',
      'نوع کویل': '100% مسی',
      'فناوری': 'اینورتر',
      'گارانتی': '1 سال + 5 سال کمپرسور'
    },
    featuresEn: {
      'Capacity': '1.5 Ton',
      'Energy Rating': '5 Star',
      'Coil Type': '100% Copper',
      'Technology': 'Inverter',
      'Warranty': '1 Year + 5 Years Compressor'
    },
    rating: 4.8,
    reviewCount: 312,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    sku: 'BOSCH-DW-12',
    name: 'ماشین ظرفشویی بوش 12 نفره',
    nameEn: 'Bosch 12 Place Dishwasher',
    slug: 'bosch-12-place-dishwasher',
    description: 'ماشین ظرفشویی توکار با ظرفیت 12 نفره، 6 برنامه شستشو، و فناوری AquaStop. بهره‌وری انرژی با رتبه A++.',
    descriptionEn: 'Built-in dishwasher with 12 place settings, 6 wash programs, and AquaStop technology. Energy efficient with A++ rating.',
    shortDescription: 'ماشین ظرفشویی 12 نفره توکار',
    shortDescriptionEn: '12 Place Settings Built-in Dishwasher',
    brand: 'Bosch',
    category: 'لوازم آشپزخانه',
    categoryEn: 'Kitchen Appliances',
    subCategory: 'ماشین ظرفشویی',
    subCategoryEn: 'Dishwashers',
    price: 44999000,
    stock: 10,
    images: ['/placeholder.svg'],
    mainImage: '/placeholder.svg',
    features: {
      'ظرفیت': '12 نفره',
      'رتبه انرژی': 'A++',
      'برنامه‌ها': '6',
      'سطح صدا': '44 دسی‌بل',
      'گارانتی': '2 سال'
    },
    featuresEn: {
      'Place Settings': '12',
      'Energy Rating': 'A++',
      'Programs': '6',
      'Noise Level': '44 dB',
      'Warranty': '2 Years'
    },
    rating: 4.4,
    reviewCount: 87,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    sku: 'WHIRL-MW-30',
    name: 'مایکروفر ویرپول 30 لیتر',
    nameEn: 'Whirlpool 30L Microwave Oven',
    slug: 'whirlpool-30l-microwave-oven',
    description: 'مایکروفر کانوکشن با ظرفیت 30 لیتر، منوهای خودکار پخت، و قابلیت تمیز کردن با بخار. عالی برای پخت و کباب کردن.',
    descriptionEn: 'Convection microwave with 30L capacity, auto-cook menus, and steam clean feature. Perfect for baking and grilling.',
    shortDescription: 'مایکروفر 30 لیتر کانوکشن با تمیزکننده بخار',
    shortDescriptionEn: '30L Convection Microwave with Steam Clean',
    brand: 'Whirlpool',
    category: 'لوازم آشپزخانه',
    categoryEn: 'Kitchen Appliances',
    subCategory: 'مایکروفر',
    subCategoryEn: 'Microwave Ovens',
    price: 18999000,
    discountPrice: 15999000,
    discountPercent: 16,
    stock: 25,
    images: ['/placeholder.svg'],
    mainImage: '/placeholder.svg',
    features: {
      'ظرفیت': '30 لیتر',
      'نوع': 'کانوکشن',
      'توان': '1400 وات',
      'پخت خودکار': '200+ منو',
      'گارانتی': '1 سال'
    },
    featuresEn: {
      'Capacity': '30L',
      'Type': 'Convection',
      'Power': '1400W',
      'Auto Cook': '200+ Menus',
      'Warranty': '1 Year'
    },
    rating: 4.3,
    reviewCount: 203,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    sku: 'DYSON-VC-V11',
    name: 'جاروبرقی بی‌سیم دایسون V11',
    nameEn: 'Dyson V11 Cordless Vacuum',
    slug: 'dyson-v11-cordless-vacuum',
    description: 'جاروبرقی بی‌سیم قدرتمند با مکش هوشمند، صفحه نمایش LCD، و زمان کار تا 60 دقیقه. شامل چندین اتصال.',
    descriptionEn: 'Powerful cordless vacuum with intelligent suction, LCD screen, and up to 60 minutes runtime. Comes with multiple attachments.',
    shortDescription: 'جاروبرقی بی‌سیم با مکش هوشمند',
    shortDescriptionEn: 'Cordless Vacuum with Intelligent Suction',
    brand: 'Dyson',
    category: 'شستشو و نظافت',
    categoryEn: 'Washing & Cleaning',
    subCategory: 'جاروبرقی',
    subCategoryEn: 'Vacuum Cleaners',
    price: 52999000,
    discountPrice: 47999000,
    discountPercent: 9,
    stock: 6,
    images: ['/placeholder.svg'],
    mainImage: '/placeholder.svg',
    features: {
      'زمان کار': 'تا 60 دقیقه',
      'نوع': 'بی‌سیم',
      'ظرفیت گرد و غبار': '0.76 لیتر',
      'فیلتراسیون': 'HEPA',
      'گارانتی': '2 سال'
    },
    featuresEn: {
      'Runtime': 'Up to 60 mins',
      'Type': 'Cordless',
      'Dust Capacity': '0.76L',
      'Filtration': 'HEPA',
      'Warranty': '2 Years'
    },
    rating: 4.9,
    reviewCount: 421,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'p7',
    sku: 'PHIL-AP-AC3256',
    name: 'دستگاه تصفیه هوا فیلیپس',
    nameEn: 'Philips Air Purifier',
    slug: 'philips-air-purifier-ac3256',
    description: 'دستگاه تصفیه هوای پیشرفته با فناوری VitaShield IPS، حذف 99.97٪ ذرات معلق در هوا، ایده‌آل برای اتاق‌های تا 95 متر مربع. نمایش کیفیت هوا در لحظه.',
    descriptionEn: 'Advanced air purifier with VitaShield IPS technology, removes 99.97% airborne particles, ideal for rooms up to 95m². Real-time air quality display.',
    shortDescription: 'تصفیه هوا برای 95 متر مربع با VitaShield IPS',
    shortDescriptionEn: 'Air Purifier for 95m² with VitaShield IPS',
    brand: 'Philips',
    category: 'سرمایش و تهویه',
    categoryEn: 'Cooling & Air Treatment',
    subCategory: 'تصفیه هوا',
    subCategoryEn: 'Air Purifiers',
    price: 32999000,
    stock: 18,
    images: ['/placeholder.svg'],
    mainImage: '/placeholder.svg',
    features: {
      'پوشش': 'تا 95 متر مربع',
      'فیلتراسیون': 'VitaShield IPS',
      'نرخ تحویل هوا': '393 متر مکعب بر ساعت',
      'حالت‌ها': '3 سرعت + خواب',
      'گارانتی': '2 سال'
    },
    featuresEn: {
      'Coverage': 'Up to 95m²',
      'Filtration': 'VitaShield IPS',
      'CADR': '393 m³/h',
      'Modes': '3 Speed + Sleep',
      'Warranty': '2 Years'
    },
    rating: 4.6,
    reviewCount: 145,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    status: 'published',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
